[build-system]
build-backend = "uv_build"
requires = [ "uv-build>=0.11.6,<0.12" ]

[project]
name = "vimes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Laya Binu", email = "layambinu@gmail.com" },
]
requires-python = ">=3.11,<3.15"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "astro-tulips>=1.0.3",
    "h5py>=3.16.0",
    "imageio>=2.37.3",
    # 2.3.2 is the earliest version with Python 3.14 support
    # https://numpy.org/doc/stable/release/2.3.2-notes.html
    "numpy>=2.3.2",
    "pillow>=12.2.0",
    # 2.5.5 is the earlist version with Python 3.14 support
    # https://github.com/pygame-community/pygame-ce/releases/tag/2.5.5
    "pygame-ce>=2.5.5",
]

[project.scripts]
vimes = "vimes.animate:main"
vimes-preprocess = "vimes.preprocess:main"

[dependency-groups]
dev = [
    "prek==0.5.3",
    "pyinstrument==5.1.2",
    "pytest==9.0.3",
    # ruff version is managed by git hooks setup,
    # but having it as a dependency can help with IDE - lint integrations.
    "ruff==0.16.8",
]
